server:
  port: 8080
spring:
  application:
    name: user-center # 设置应用名为 user-center，用于服务注册、日志标识等场景。
  datasource:
    url: jdbc:mysql://localhost:3306/yupi?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrlInLocalInfile=true&allowPublicKeyRetrieval=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&allowUrlInLocalInfile=true&allowPublicKeyRetrieval=true&allowMultiQueries=true&allowPublicKeyRetrieval=true&allowUrlInLocalInfile=true&allowPublicKeyRetrieval=true&allowMultiQueries=true&allowPublic
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  session:
    timeout: 86400 # 86400秒 session失效
    store-type: redis # 从redis 读写session；默认是 none，表示存储在单台服务器内存
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  profiles:
    active: dev # 默认环境
  # redis 配置
  redis:
    port: 6379
    host: 127.0.0.1
    database: 1
    password: 123456 # Redis 密码
    timeout: 3000ms # 连接超时时间
    lettuce: # 使用 Lettuce 连接池
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8   # 连接池最大空闲连接数
        min-idle: 0   # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间
#    cookie:
#      # 关键1：绑定到前端访问的域名（必须和前端一致）
#      domain: 43.163.195.79
#      # 关键2：所有路径都能携带 Cookie
#      path: /
#      # 关键3：Cookie 有效期和 Session 保持一致（86400 秒 = 1 天）
#      max-age: 86400
#      # 关键4：适配跨域/代理场景
#      same-site: none
#      # 非 HTTPS 环境关闭 Secure
#      secure: false
#      # 防止 XSS 攻击（推荐）
#      http-only: true
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 关闭 [MP查询数据库时 将驼峰命名自动转换为下划线]
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志打印到控制台
  global-config: #全局配置
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除字段名(isDelete 为实体类属性名称)
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0
      update-strategy: not_null # 只更新非 null 字段